# Generated by Django 3.2.14 on 2022-07-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description_short', models.CharField(max_length=500, verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Длинное описание')),
                ('lng', models.FloatField(verbose_name='Широта')),
                ('lat', models.FloatField(verbose_name='Долгота')),
            ],
        ),
    ]
