# Generated by Django 3.2.14 on 2022-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_placeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order_number']},
        ),
        migrations.RenameField(
            model_name='place',
            old_name='placeId',
            new_name='placeid',
        ),
        migrations.AlterField(
            model_name='image',
            name='order_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
