# Generated by Django 3.2.14 on 2022-07-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20220720_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='placeid',
        ),
    ]
